name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd 
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v1

      - name: List Files After Checkout
        run: |
          pwd
          ls -a

      - name: Simple SJ Action
        id: greet
        # can reference local action or action on github repo('@' pointing to specific version(preferable), branch, commit)
        # [github username]/[specific-action]@[version]
        uses: actions/hello-world-javascript-action@v1
        # provide input to an action
        with:
          who-to-greet: Dzon
        # actions can produce outputs
          

        
